import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./compo/navBar";
import SideBar from "./compo/sideBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="flex ">
          <div className="w-1/6 mt-5">
            <SideBar />
          </div>
          <div className="w-5/6 m-5 p-5 outline outline-gray-300 h-[100vh] ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
